# this is the boilerplate crd def that controller-gen reads and modifies with the
# contents from share_type.go
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shares.sharedresource.storage.openshift.io
  annotations:
    displayName: Shares
    description: Extension for sharing ConfigMaps and Secrets across Namespaces
spec:
  scope: Cluster
  group: sharedresource.storage.openshift.io
  names:
    plural: shares
    singular: share
    kind: Share
    listKind: ShareList
  versions:
  - name: v1alpha1
    served: true
    storage: true
